# Generated by Django 4.2.7 on 2023-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_keyword_video_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
